# Generated by Django 2.2 on 2019-05-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classe',
            field=models.CharField(default='U', max_length=5),
        ),
    ]
