# Generated by Django 2.2 on 2019-05-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0002_course_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
